### PR TITLE
made GOODEREIER

### PR DESCRIPTION
**Pull request by saverofthewos**
you should really merge

### CODE REVIEW

**Comment by npxl32** [comment]
no

**Comment by saverofthewos** [comment]
yes theres no conflicts with base branch so u should

**Comment by npxl32** [comment]
make a "no" button that takes you to bing or something, then ill merge

**Comment by saverofthewos** [comment]
ok

**Comment by saverofthewos** [comment]
ok merge now @npxl32

**Comment by npxl32** [comment]
wait test it. i believe your code is broken

**Comment by saverofthewos** [comment]
i too dumb

**Comment by npxl32** [comment]
@saverofthewos Wait just re-deploy the GitHub Pages for your fork to test it.

**Comment by saverofthewos** [comment]
i did it ditn work

**Comment by npxl32** [comment]
Set the GitHub Pages default branch to main

**Comment by saverofthewos** [comment]
oops i had it set to krillyourself

**Comment by npxl32** [comment]
Tested it locally. Your code doesn't work because you're sending and listening for the same postMessage, exactly what I thought the problem was.
Additionally, the "Maybe" and "None of the above" options don't do anything because they don't have event listeners.

**Comment by saverofthewos** [comment]
i too lazy fix

**Comment by npxl32** [comment]
Then no merge

**Pull request closed without merging**
