### PR TITLE
Vdmkvfdvd

### PR DESCRIPTION
**Pull request by saverofthewos**

### CODE REVIEW

**Comment by npxl32** [comment]
this is literally just a readme change
like why

**Comment by saverofthewos** [comment]
did you see what i changed

**Comment by npxl32** [comment]
yes but i didn't write that, i typoed "ok" as "ko"

**Comment by saverofthewos** [comment]
no you did write that

**Comment by npxl32** [comment]
no i did not

**Comment by saverofthewos** [comment]
you didnt type it but your subconsious wanted to

**Comment by npxl32** [comment]
no

**Comment by npxl32** [comment]
lets focus on: uh oh we just opened a new game studio and dont know how to use godot because we dont want to use unity (because general consensus says no unity, i say either is fine)

**Pull request closed without merging**
